### ISSUE TITLE
Get the "runtime" type of an object

### ISSUE THREAD

**Issue by dkgof** [dkraczkowski/js.class#1]
Hi i have 2 classes A and B, B is a subclass of A.

var A = Class({});
var B = A.extend({});

If i want to test if my current object is actually of type A and not type B how would i do this without specificially checking that its not any of its subtypes:

var x = new A();
var y = new B();

x.typeOf(A); //true
x instanceof A; //true

y.typeOf(A); //true
y instanceof A; //true

So from my perspective i cant tell that x is of type A only, without starting to test for all the subclasses i dont want it to be.

in java i would do something like:

x.getClass() == A.class; //True
y.getClass() == A.class; //False (Since its class is B)

**Comment by dkraczkowski** [comment]
@dkgof https://github.com/dkraczkowski/js.class/releases/tag/2.5.1
Check the newest tag and the following example, this should help you a bit:

``` js
var A = Class({});
var B = A.extend({});
var x = new A();
var y = new B();

x.constructor == A; // true
x.constructor == B;//false

y.constructor == A;//false
y.constructor == B;//true
```

**Comment by dkgof** [comment]
Great, thanks a lot!
