### ISSUE TITLE
Register with Bower Registry

### ISSUE THREAD

**Issue by mikepmtl** [dkraczkowski/js.class#3]
Would it be possible to register js.class with Bower?

I was able to install it using the direct gihub url: 
bower install https://github.com/dkraczkowski/js.class.git#2.5.2

But I would like to simply keep it in my bower.json file and have it install by itself. (Easier when dealing with many machines).

Regards,
Mike

**Comment by dkraczkowski** [comment]
@mikepmtl I have registered the package in bower repository.
