### ISSUE TITLE
[Feature Request] Get class object from an instance

### ISSUE THREAD

**Issue by amekusa** [dkraczkowski/js.class#7]
Hi.
It would be so nice if we can retrieve the class object from an instance.
Like this:

``` js
var Dog = JSClass({
    ...
}).static({
    species: 'C. lupus'
});

var myPet = new Dog();
console.log( myPet.getClass().species ); // "C. lupus"

if (myPet.getClass() === Dog) { // true
    ...
}
```

Or can I already do the same thing somehow?

**Comment by dkraczkowski** [comment]
@amekusa Check https://github.com/dkraczkowski/js.class/releases/tag/2.7.0

**Comment by amekusa** [comment]
Amazing! Thank you for your fast corresponding. Nice work :thumbsup:
